[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.97"
clap = "4.5.35"
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.27"
reqwest = "0.12.15"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.0.0"
url = "2.5.4"
zeroconf = "0.15.1"

rs4a-vapix = { path = "crates/vapix" }

[workspace.package]
edition = "2021"
