[package]
name = "rs4a"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
env_logger = "0.11.8"
itertools = "0.14.0"
log = "0.4.27"
zeroconf = "0.15.1"
