[package]
name = "rs4a-vapix"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = {workspace = true}
serde_json = {workspace = true, features = ["raw_value"]}
reqwest = {workspace = true}
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
url = "2.5.4"